apiVersion: v1
kind: Pod
metadata:
  name: kaniko-$(Build.BuildId)
  namespace: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=azure-vote/Dockerfile"
    - "--context=git://github.com/michaelburch/azure-voting-app-redis/"
    - "--destination=demoacr50744.azurecr.io/azure-vote-front:v1"
    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
  - name: docker-config
    configMap:
      name: acrdocker